### PR TITLE
Same ids bug

### PR DESCRIPTION
**Pull request by secmi**

### CODE REVIEW

**Comment by dbosen** [comment]
Looks good, but I will try to get some real world data to test this first.

**Comment by secmi** [comment]
Hello @dbosen, is possible to merge this bugfix and make a new release in in the near future?

**Comment by dbosen** [comment]
I will make this a priority today.

**Comment by secmi** [comment]
Great, thank you.

**Review by dbosen — APPROVED** [review]
Looks good

**Comment by dbosen** [comment]
@martincollar feel free to create a new tag for this, thanks!

**Pull request merged**
