### PR TITLE
Support publish/unpublish/delete based on Nexx.tv video data

### PR DESCRIPTION
**Pull request by martincollar**

### CODE REVIEW

**Comment by martincollar** [comment]
Any suggestions how to improve readme drush commands descriptions? I did my best but I can feel it should be described better for people who doesnt know this module.

**Comment by martincollar** [comment]
I have problems with update tests see testInactiveVideoUpdate and other testXXXXXVideoUpdate, any ideas? I'm sending proper status with same Omnia id via getTestVideoData method but I'm probably missing something..

**Comment by dbosen** [comment]
Did you fix the problem? It seems to be good now.

**Comment by martincollar** [comment]
No, I commented out testInactiveVideoUpdate and other xxxUpdate tests somehow doesn't work, looks like second call to omnia endpoint with same video id doesn't update proper node it looks like its creating new one and I don't know why.

Can you quickly look to testInactiveVideoUpdate? I would like to create and Video entity with Omnia video id 4 Here... There are two getTestVideoData calls (I added params to this method to work with all my tests) so Im sending here active=1 for the first time and active=0 for the second time, do you have an idea why second assert where i'm checking status shows that status is 1? I've tested with real nexx server what i changed in Omnia controller and it works.. so its the problem of tests..

BTW testInactiveVideoCreate works, assert check status and its 0 because of active=0 in getTestVideoData.

**Review by dbosen — APPROVED** [review]
Looks good!

**Pull request merged**
